services:
  example-static-service:
    build: .

    labels:
      - "baker.enable=true"
      - "baker.network=baker"
      - "baker.service.port=8000"
      - "baker.service.static.domain=example.com"
      - "baker.service.static.path=/*"

    networks:
      - baker

networks:
  baker:
    name: baker
    external: true     