services:
  example-websocket-service:
    build: .

    labels:
      - "baker.enable=true"
      - "baker.network=baker"
      - "baker.service.port=3000"
      - "baker.service.static.domain=example.com"
      - "baker.service.static.path=/*"
      - "baker.service.static.headers.host=example.com"

    networks:
      - baker
    
    ports:
      - "3000:3000"

networks:
  baker:
    name: baker
    external: true     